version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
      container_name: django
      build:
        context: ./django_celery_trial1
#        dockerfile: Dockerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./django_celery_trial1:/usr/src/app
      ports:
        - "8001:8000"
      environment:
        - DEBUG=1
        - SECRET_KEY=74849fjfkf93039fjfkf
        - ALLOWED_HOSTS=localhost,127.0.0.1
      depends_on:
        - redis